CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "username" varchar NOT NULL,
  "birthdate" DATE,
  "mail" varchar NOT NULL,
  "phone" varchar,
  "profile_icon" varchar,
  "profile_banner" varchar,
  "password" varchar NOT NULL,
  "is_online" bool,
  "is_activated" bool
);

CREATE TABLE "user_group" (
  "user_id" int,
  "role" varchar,
  "group_id" int
);

CREATE TABLE "groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "private" bool,
  "last_sent" timestamptz
);

CREATE TABLE "user_group_messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender" int,
  "reply_to" int,
  "group_id" int,
  "timestamp" timestamptz NOT NULL DEFAULT (now()),
  "content" json
);

CREATE TABLE "pages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "profile_icon" varchar,
  "profile_banner" varchar,
  "content" json
);

CREATE TABLE "users_page" (
  "user_id" int,
  "role" varchar,
  "page_id" int
);

CREATE TABLE "post" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "author_id" int,
  "author_type" varchar,
  "post_type" int,
  "timestamp" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "publications" (
  "post_id" int,
  "content" json
);

CREATE TABLE "commentary" (
  "id" int,
  "post_id" int,
  "content" json
);

CREATE TABLE "private_messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender" int,
  "receiver" int,
  "timestamp" timestamptz NOT NULL DEFAULT (now()),
  "content" json
);

CREATE TABLE "last_seen" (
  "user_id" int,
  "last_seen_at" timestamptz
);

CREATE TABLE "friends" (
  "owner_id" int,
  "friend_id" int
);

CREATE TABLE "users_posts_likes" (
  "user_id" int,
  "post_id" int
);

ALTER TABLE "user_group" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_group" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "user_group_messages" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");

ALTER TABLE "users_page" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_page" ADD FOREIGN KEY ("page_id") REFERENCES "pages" ("id");

ALTER TABLE "publications" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("id");

ALTER TABLE "commentary" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("id");

ALTER TABLE "user_group_messages" ADD FOREIGN KEY ("reply_to") REFERENCES "user_group_messages" ("id");

ALTER TABLE "user_group_messages" ADD FOREIGN KEY ("sender") REFERENCES "users" ("id");

ALTER TABLE "private_messages" ADD FOREIGN KEY ("sender") REFERENCES "users" ("id");

ALTER TABLE "private_messages" ADD FOREIGN KEY ("receiver") REFERENCES "users" ("id");

ALTER TABLE "last_seen" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "friends" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "friends" ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("id");

ALTER TABLE "commentary" ADD FOREIGN KEY ("id") REFERENCES "post" ("id");

ALTER TABLE "users_posts_likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_posts_likes" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("id");
